[tool.black]
exclude = '(\.eggs|\.git|\.hg|\.mypy|_cache|\.nox|\.tox|\.venv|\.svn|_build|buck-out|build|dist|_vendor|servicepb)'

[tool.vendoring]
destination = "keepsake/_vendor/"
requirements = "keepsake/_vendor/vendor.txt"
namespace = "keepsake._vendor"

protected-files = ["__init__.py", "README.rst", "vendor.txt"]
patches-dir = ""

[tool.vendoring.transformations]
substitute = []
drop = [
  # pyyaml falls back to plain python
  "_yaml.*.so",
]

[tool.vendoring.typing-stubs]

[tool.vendoring.license.directories]

[tool.vendoring.license.fallback-urls]
